// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WbsApp.Data;

#nullable disable

namespace WbsApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001074226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WbsApp.Models.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("IN_PROGRESS")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId")
                        .HasName("pk_projects");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.HasIndex("UpdatedAt", "ProjectId")
                        .HasDatabaseName("ix_projects_updated_at");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_date_range", "end_date >= start_date");

                            t.HasCheckConstraint("ck_projects_status", "status IN ('IN_PROGRESS', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("WbsApp.Models.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("assignee_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Memo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("memo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_task_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("MEDIUM")
                        .HasColumnName("priority");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NOT_STARTED")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("TaskId")
                        .HasName("pk_tasks");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("ix_tasks_parent_task_id");

                    b.HasIndex("ProjectId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_tasks_root_order")
                        .HasFilter("parent_task_id IS NULL");

                    b.HasIndex("ProjectId", "EndDate", "Status")
                        .HasDatabaseName("ix_tasks_project_end_status");

                    b.HasIndex("ProjectId", "ParentTaskId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_tasks_child_order")
                        .HasFilter("parent_task_id IS NOT NULL");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_completion", "(progress = 100) = (status = 'COMPLETED')");

                            t.HasCheckConstraint("ck_tasks_date_range", "end_date >= start_date");

                            t.HasCheckConstraint("ck_tasks_not_self_parent", "parent_task_id IS NULL OR parent_task_id <> task_id");

                            t.HasCheckConstraint("ck_tasks_priority", "priority IN ('HIGH', 'MEDIUM', 'LOW')");

                            t.HasCheckConstraint("ck_tasks_progress", "progress BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_tasks_sort_order", "sort_order >= 1");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('NOT_STARTED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("WbsApp.Models.Entities.TaskItem", b =>
                {
                    b.HasOne("WbsApp.Models.Entities.TaskItem", "ParentTask")
                        .WithMany("ChildTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_parent");

                    b.HasOne("WbsApp.Models.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WbsApp.Models.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WbsApp.Models.Entities.TaskItem", b =>
                {
                    b.Navigation("ChildTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
